# Local Jekyll config file (will be appended after master)

# Site settings
title: "Facts on climate"
url: https://factsonclimate.org
email: info@factsonclimate.org
github: faktaoklimatu/web-en
twitter: "faktaoklimatu"
newsletter: "https://tinyletter.com/faktaoklimatu/subscribe"
fundraising: "https://www.darujme.cz/projekt/1204215"
author: factsonclimate.org
copyright: "&copy; 2021 Otevřená data o klimatu, z. ú."
description: We collect data on climate and climate change provided by scientific institutions and transform them into infographics for further use.
keywords: climate, climate change, infographics

# Set permalinks in local language
collections:
    pages:
        output: true
        permalink: /:title

# Enable Czech smart quotes
kramdown:
    smart_quotes: lsquo,rsquo,ldquo,rdquo
